server:
  port: 8082
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/xdclass?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  application:
    name: mybatisname
mybatis:
  type-aliases-package: com.mybatis.domain
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
